### ISSUE TITLE
Feature Req: Support text template for parsing

### ISSUE THREAD

**Issue by mr-karan** [knadh/stuffbin#2]
[ParseTemplates](https://github.com/knadh/stuffbin/blob/master/fs.go#L269) is a helper function to read a template file and convert to `template.Template` object. The [import](https://github.com/knadh/stuffbin/blob/master/fs.go#L7) for `template` is `html/template` which seems like an opinionated choice. In some cases the user might not want the encoding/escaping to make characters as HTML safe and instead want to render the values _as-is_, for which `text/template` should be enough. 

Ideally `parseTemplates` should take a parameter to choose the correct package? We can default to `html/template` to keep it backward compatible.

Is that something `stuffbin` would want to support? Can send PR in that case :+1: 

Current workaround: Read the file normally using `stuffbin` and do the template parsing myself in the user code.

**Comment by knadh** [comment]
I agree. It won't be easy to have one function that takes a type because `template.Template` can refer to `text/template` or `html/template` packages. We'll end up with `ParseTextTemplates()` `ParseHTMLTemplates()` etc. Breaks the API, but would be the correct way to do it.

Strange that `Template` isn't an interface.
